var GAME_LEVELS = [
  ["                                                                               x",
   "                                                                               x",
   "         yyy        y y  yyy   yyy   y                                         x",
   "        y   y       y y  y    y   y  y                                    o    x",
   "       y        yy  y y  yyy y      yyy                            xxxxxxxxxxxxx",
   "        y   y  y  y y y  y    y   y  y                     xxxxx                ",
   "         yyy    yy  y y  yyy   yyy   y                 o                        ",
   "                                                   xxxxx                        ",
   "                  y                     o                xxxxx                  ",
   "                   y   y             xxxxx                     xxxx             ",
   "                    y y        p                                      xxxxx   o ",
   "                 y y y       xxxxx                                           xxx",
   "                      o                                               xxxxx     ",
   "                    xxxxx                                      xxxxx            ",
   "                                                     o     xxxxx                ",
   "             xxxxx                                 xxxxx                        ",
   "     @       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                      ooo                                                                                         ",
    "                  xxxxxxxxxxx                                                                                     ",
    "                  x                                                                                               ",
    "                 xx                                                                                               ",
    "                  x    oo                                                                                         ",
    "                  x   xxxx  x                            xx    oo    xx          xx          xx    oo    xx       ",
    "                  x!!!!!!!!!x            p               xx    xx    xx    xx    xx    xx    xx    xx    xx     o ",
    "           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!xx!!!!!!!!!!xx!!!!!!!!!!xx!!!!!!!!!!xx    xxx",
    "                                                         x x!!!!!!!!x  x!!!!!!!!x  x!!!!!!!!x  x!!!!!!!!x      x  ",
    "   xxx                                                   x  x!!!!!!x    x!!!!!!x    x!!!!!!x    x!!!!!!x       x  ",
    "          o                                            o x   x!!!!x      x!!!!x      x!!!!x      x!!!!x       ox  ",
    "         xxx  xxx  xxxxx   x  xxxx  xxx  xxx         xxxxx    xvvx        xvvx        xvvx        xvvx       xxx  ",
    "          v          v         v          v          x                                                         x  ",
    "                                                xx   x                                                         x  ",
    "                                                     x                                                         x  ",
    "x                                                    x  o  |                                                   x  ",
    "x      @       oo           o        oo           o  xxxxxxx                                                   x  ",
    "xxxxxxxx      xxxx         xxx      xxxx       xxxxxxxx     xxxx                                               x  ",
    "       x     xxxxxx        xxx     xxxxx      xx                  xxx         xxxx                      xxxxxxxxx ",
    "       x      xxxx         xxx      xxxx       x                      xxxxx        xxx           xxx              ",
    "       x      xxxx        xxxx      xxxxx      x                                            xxx                   ",
    "       x      xxxx         xxx      xxxx       x                                                                  ",
    "       x      xxxxx        xxx      xxxx      xx                                                                  ",
    "       x      xxxx         xxx      xxxx       x                                                                  ",
    "       x!!!!!!xxxx!!!!!!!!!xxx!!!!!!xxxx!!!!!!!x                                                                  ",
    "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                  "],
    ["                                                                                                              ",
     "                                                                                                              ",
     "                                                                                                              ",
     "   x                                                                                                          ",
     "   x                                                                                                      o   ",
     "   x                                                                                                    xxxxx ",
     "   x                                                                                                x         ",
     "   x                                                                                            x             ",
     "   x                   xxxxxxxxxxxxxx     xxxxxx                                            x                 ",
     "   x                                                                                    x                     ",
     "   x                                               xxxxxxxxxx            o         x                          ",
     "   x                                         |x|                   x     x     x                              ",
     "   x                       |xx| xxxxxxxxxx                         x!!!!!!!!!!!x                              ",
     "   x                                                               x!!!!!!!!!!!x                              ",
     "   x            xxxxxxxxx                                          xxxx!xxx!xxxx                              ",
     "   x                                                                   v   v                                  ",
     "   x                                                                                                          ",
     "   x                                         p                                                                ",
     "   x                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 xxxxxxxxxxxxxxx             ",
     "   x                  xx                                         x               x               xo          x",
     "   x                xx                                   o        x             x                xx          x",
     "   x              xx                                     x         x           x                 x=          x",
     "   x            xx                                      x x         x    o    x                  x           x",
     "   x          xx                           p           x   x         x   x   x                   xo          x",
     "   x        xx                            xxx         x     x                                    xx          x",
     "   x oooo xx              pppppppp        x!x        x       x                                   x           x",
     "   xxxxxxxx               xxxxxxxx        x!x       x         x                                  x=          x",
     "                          x!!!!!!x        x!x      x           x                                 xo          x",
     "                          x!!!!!!x        x!x      x           x                                 xx          x",
     "                          xxxvxxxx        xvx      x           x                                 x           x",
     "                                                  xx           xx                                x           x",
     "                                                   x           x                                 xxxxx        ",
     "                                                  ox           xo                          p                  ",
     "                                                  xx           xx      xxxxx    xxxxxxxxxxxxxxxxxxxx          ",
     "                                                   x           x       x    x                             xxx ",
     "                                                o  x           x   o   x     x                       o o      ",
     "                                             xxxxxxx           xxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
     "                                                   x                                                          ",
     "                                    o              x                                                          ",
     "                          xxxxxx  xxxxxx  xxxxxx   x                                                          ",
     "                         o                      o  x                                                          ",
     "                      xxxxxxxx              xxxxxxxx                                                          ",
     "                                    o              x                                                          ",
     "        @                       xxxxxxxxxx         x                                                          ",
     "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxx                                                          ",
     "                                                                                                              ",
     "                                                                                                              "],
     ["                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                                                              ",
      "                                                                          o   o     o                         ",
      "                      x  o  x  o    o   o      o       xoooooooxooooooox  x   xx    x                         ",
      "                       x o x   xxxxxx   x  oo  x        xooooox xooooox   x   x x   x                         ",
      "  x                     x x    x oo x   x  oo  x         xooox   xooox    x   x  x  x                         ",
      "  x                      x     x oo x    x oo x           xox     xox     x   x   x x                         ",
      "  x                      x     xxxxxx     xxxx             x       x      x   x    xx                         ",
      "  x  @                                                                                                        ",
      "  xxxxxxx                                                                                                     ",
      "        x                                                                                                     ",
      "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!",
      "                                                                                                              ",
      "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
